module RockGazebo
    module Syskit
        module ProfileExtension
            # The name of the SDF world we're under
            #
            # This is used as the transformer root frame as well
            #
            # @return [String]
            def sdf_world_name
                sdf_world.name
            end

            # The globally-loaded SDF model that describes our world
            def sdf_world
                @sdf_world ||= (Conf.sdf.get(:world) || SDF::World.empty)
            end

            # The model loaded with #use_sdf_model
            attr_accessor :sdf_model

            # @api private
            #
            # Resolve the 'path' argument of use_sdf_model into a model object
            def resolve_sdf_model(*path)
                if path.size == 1 && !path.first.respond_to?(:to_str)
                    # Assume this is a SDF::Model object
                    path.first
                else
                    _, resolved_paths = Rock::Gazebo.resolve_worldfiles_and_models_arguments([File.join(*path)])
                    full_path = resolved_paths.first
                    if !File.file?(full_path)
                        raise ArgumentError, "#{File.join(*path)} cannot be resolved to a valid gazebo world"
                    end

                    models = SDF::Root.load(full_path).each_model.to_a
                    if models.size > 1
                        raise ArgumentError, "#{full_path} has more than one top level model, cannot use in use_sdf_model"
                    elsif models.empty?
                        raise ArgumentError, "#{full_path} has no top level model, cannot use in use_sdf_model"
                    end
                    models.first
                end
            end

            # Setup the transformer based on the given model
            def use_sdf_model(*path)
                # This is a guard used by
                # ConfigurationExtension#use_sdf_world to verify that
                # it was was called first. Otherwise, devices for the
                # world models won't be defined and stuff like vizkit3d_world
                # won't be configured properly
                Conf.sdf.has_profile_loaded = true

                model = resolve_sdf_model(*path)
                @sdf_model = model
                transformer.parse_sdf_model(model)
                model
            end

            # Configure the transformer to reflect the SDF environment loaded
            # using Conf.syskit.use_sdf_world
            def use_sdf_world
                world = sdf_world
                exclude_models = []
                if sdf_model
                    exclude_models << sdf_model.name
                end
                transformer.parse_sdf_world(world, exclude_models: exclude_models)
            end

            # Sets up this profile, robot and transformer according to the
            # information in the model at "path"
            #
            # In addition to {#use_sdf_model}, it adds the Gazebo devices that
            # expose a simulation
            def use_gazebo_model(*path)
                world_name = self.sdf_world_name
                model = use_sdf_model(*path)

                # Load the model in the syskit subsystems
                if Conf.sdf.world?
                    robot.load_gazebo(model, world_name: world_name, models: Conf.sdf.world.each_model.to_a)
                else
                    robot.load_gazebo(model, world_name: world_name)
                end

                if !(device = robot.find_device(model.name))
                    raise RuntimeError, "cannot resolve device #{model.name}, it should have been created by RobotDefinitionExtension#load_gazebo, got #{robot.each_master_device.map(&:name).sort.join(", ")}"
                end
                device.frame_transform model.name => world_name
                transformer.dynamic_transform device, model.name => world_name

                # Declare the transformations that can be generated by the
                # ModelTask on the transformer
                model.each_link do |link|
                    if dev = robot.find_device("#{link.name}_link")
                        dev.frame_transform link.full_name => world_name
                        transformer.dynamic_transform dev, link.full_name => world_name
                    else
                        raise ArgumentError, "expected to have a device called #{link.name}_link providing Rock::Devices::Gazebo::Link, but it does not exist. Got #{robot.each_master_device.map(&:name).sort.join(", ")}"
                    end
                end
            end

        end
        ::Syskit::Actions::Profile.include ProfileExtension
    end
end
